DEFINE TABLE CICD_DEMO_DB.PUBLIC.CUSTOMERS (
    id NUMBER AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DEFINE VIEW CICD_DEMO_DB.PUBLIC.ACTIVE_CUSTOMERS AS
    SELECT id, name, email, created_at
    FROM CICD_DEMO_DB.PUBLIC.CUSTOMERS
    WHERE created_at > DATEADD(day, -90, CURRENT_TIMESTAMP());
